# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Addmanual.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Addmanual(object):
    def setupUi(self, Addmanual):
        Addmanual.setObjectName("Addmanual")
        Addmanual.resize(425, 208)
        Addmanual.setStyleSheet("background-color: rgb(254,251,234);")
        self.centralwidget = QtWidgets.QWidget(Addmanual)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setMinimumSize(QtCore.QSize(0, 0))
        self.save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 5, 3, 1, 1)
        self.insercalories = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.insercalories.setStyleSheet("background-color: white;")
        self.insercalories.setObjectName("insercalories")
        self.gridLayout.addWidget(self.insercalories, 3, 1, 1, 2)
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 5, 4, 1, 1)
        self.portion = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.portion.setFont(font)
        self.portion.setObjectName("portion")
        self.gridLayout.addWidget(self.portion, 4, 3, 1, 1)
        self.calories = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.calories.setFont(font)
        self.calories.setObjectName("calories")
        self.gridLayout.addWidget(self.calories, 3, 0, 1, 1)
        self.protein = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.protein.setFont(font)
        self.protein.setObjectName("protein")
        self.gridLayout.addWidget(self.protein, 4, 0, 1, 1)
        self.carbs = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.carbs.setFont(font)
        self.carbs.setObjectName("carbs")
        self.gridLayout.addWidget(self.carbs, 5, 0, 1, 1)
        self.insercarbs = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.insercarbs.setStyleSheet("background-color: white;")
        self.insercarbs.setObjectName("insercarbs")
        self.gridLayout.addWidget(self.insercarbs, 5, 1, 1, 2)
        self.insertportion = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.insertportion.setStyleSheet("background-color: white;")
        self.insertportion.setObjectName("insertportion")
        self.gridLayout.addWidget(self.insertportion, 4, 4, 1, 1)
        self.fat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fat.setFont(font)
        self.fat.setObjectName("fat")
        self.gridLayout.addWidget(self.fat, 3, 3, 1, 1)
        self.name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 2, 0, 1, 1)
        self.insertprotein = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.insertprotein.setStyleSheet("background-color: white;")
        self.insertprotein.setObjectName("insertprotein")
        self.gridLayout.addWidget(self.insertprotein, 4, 1, 1, 2)
        self.insertfat = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.insertfat.setStyleSheet("background-color: white;")
        self.insertfat.setObjectName("insertfat")
        self.gridLayout.addWidget(self.insertfat, 3, 4, 1, 1)
        self.insertname = QtWidgets.QLineEdit(self.centralwidget)
        self.insertname.setStyleSheet("background-color: white;")
        self.insertname.setObjectName("insertname")
        self.gridLayout.addWidget(self.insertname, 2, 1, 1, 4)
        self.addmanual = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addmanual.setFont(font)
        self.addmanual.setStyleSheet("color: rgb(74, 130, 131);")
        self.addmanual.setAlignment(QtCore.Qt.AlignCenter)
        self.addmanual.setObjectName("addmanual")
        self.gridLayout.addWidget(self.addmanual, 1, 0, 1, 5)
        Addmanual.setCentralWidget(self.centralwidget)

        self.retranslateUi(Addmanual)
        QtCore.QMetaObject.connectSlotsByName(Addmanual)

    def retranslateUi(self, Addmanual):
        _translate = QtCore.QCoreApplication.translate
        Addmanual.setWindowTitle(_translate("Addmanual", "MainWindow"))
        self.save.setText(_translate("Addmanual", "Save"))
        self.cancel.setText(_translate("Addmanual", "Cancel"))
        self.portion.setText(_translate("Addmanual", "Portion"))
        self.calories.setText(_translate("Addmanual", "Calories"))
        self.protein.setText(_translate("Addmanual", "Protein"))
        self.carbs.setText(_translate("Addmanual", "Carbs"))
        self.fat.setText(_translate("Addmanual", "Fat"))
        self.name.setText(_translate("Addmanual", "Name"))
        self.addmanual.setText(_translate("Addmanual", "Add Manual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Addmanual = QtWidgets.QMainWindow()
    ui = Ui_Addmanual()
    ui.setupUi(Addmanual)
    Addmanual.show()
    sys.exit(app.exec_())
