# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'foodlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 820)
        MainWindow.setWindowIcon(QtGui.QIcon("Logokecil.png"))
        MainWindow.setStyleSheet("background-color: rgb(254,251,234);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 45))
        self.header.setMaximumSize(QtCore.QSize(16777215, 45))
        self.header.setStyleSheet("")
        self.header.setObjectName("header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.line = QtWidgets.QFrame(self.header)
        self.line.setStyleSheet("background-color: rgb(82, 143, 145);")
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout.addWidget(self.header)
        self.main_body = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setStyleSheet("")
        self.main_body.setObjectName("main_body")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.calorieboxs = QtWidgets.QWidget(self.main_body)
        self.calorieboxs.setObjectName("calorieboxs")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.calorieboxs)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.consumbedbox = QtWidgets.QWidget(self.calorieboxs)
        self.consumbedbox.setMinimumSize(QtCore.QSize(220, 0))
        self.consumbedbox.setStyleSheet("QWidget {\n"
"    border: 2px solid grey;\n"
"    background-color: #F0FDFA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"Qlabel {\n"
"    border: none; \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.consumbedbox.setObjectName("consumbedbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.consumbedbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.consumed = QtWidgets.QLabel(self.consumbedbox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.consumed.setFont(font)
        self.consumed.setStyleSheet("color: rgb(153, 153, 153);\n"
"border: none;")
        self.consumed.setAlignment(QtCore.Qt.AlignCenter)
        self.consumed.setObjectName("consumed")
        self.verticalLayout_3.addWidget(self.consumed)
        self.calorie_2 = QtWidgets.QLabel(self.consumbedbox)
        self.calorie_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.calorie_2.setFont(font)
        self.calorie_2.setStyleSheet("color: #0F766E;\n"
"border: none;")
        self.calorie_2.setAlignment(QtCore.Qt.AlignCenter)
        self.calorie_2.setObjectName("calorie_2")
        self.verticalLayout_3.addWidget(self.calorie_2)
        self.horizontalLayout.addWidget(self.consumbedbox)
        self.goalbox = QtWidgets.QWidget(self.calorieboxs)
        self.goalbox.setStyleSheet("QWidget {\n"
"    border: 2px solid grey;\n"
"    background-color: #F0FDFA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"Qlabel {\n"
"    border: none; \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.goalbox.setObjectName("goalbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.goalbox)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.goal = QtWidgets.QLabel(self.goalbox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.goal.setFont(font)
        self.goal.setStyleSheet("color: rgb(153, 153, 153);\n"
"border: none;")
        self.goal.setAlignment(QtCore.Qt.AlignCenter)
        self.goal.setObjectName("goal")
        self.verticalLayout_4.addWidget(self.goal)
        self.calorie_3 = QtWidgets.QLabel(self.goalbox)
        self.calorie_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.calorie_3.setFont(font)
        self.calorie_3.setStyleSheet("color: black;\n"
"border: none;")
        self.calorie_3.setAlignment(QtCore.Qt.AlignCenter)
        self.calorie_3.setObjectName("calorie_3")
        self.verticalLayout_4.addWidget(self.calorie_3)
        self.horizontalLayout.addWidget(self.goalbox)
        self.remainingbox = QtWidgets.QWidget(self.calorieboxs)
        self.remainingbox.setStyleSheet("QWidget {\n"
"    border: 2px solid grey;\n"
"    background-color: #F0FDFA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"Qlabel {\n"
"    border: none; \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.remainingbox.setObjectName("remainingbox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.remainingbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.remaining = QtWidgets.QLabel(self.remainingbox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.remaining.setFont(font)
        self.remaining.setStyleSheet("color: rgb(153, 153, 153);\n"
"border: none;")
        self.remaining.setAlignment(QtCore.Qt.AlignCenter)
        self.remaining.setObjectName("remaining")
        self.verticalLayout_5.addWidget(self.remaining)
        self.calorie = QtWidgets.QLabel(self.remainingbox)
        self.calorie.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.calorie.setFont(font)
        self.calorie.setStyleSheet("color: #22C55E;\n"
"border: none;")
        self.calorie.setAlignment(QtCore.Qt.AlignCenter)
        self.calorie.setObjectName("calorie")
        self.verticalLayout_5.addWidget(self.calorie)
        self.horizontalLayout.addWidget(self.remainingbox)
        self.verticalLayout_9.addWidget(self.calorieboxs)
        self.widget = QtWidgets.QWidget(self.main_body)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchfood = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.searchfood.setFont(font)
        self.searchfood.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchfood.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(100, 173, 173);\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    font-weight: bold;\n"
"    border-bottom: 2px solid #444;\n"
"    border-right: 2px solid #444;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(82, 143, 145);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 135, 135); \n"
"    border-bottom: 1px solid #508080;\n"
"    border-right: 1px solid #508080;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Searchicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchfood.setIcon(icon)
        self.searchfood.setIconSize(QtCore.QSize(50, 50))
        self.searchfood.setObjectName("searchfood")
        self.horizontalLayout_2.addWidget(self.searchfood)
        self.addmanual = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.addmanual.setFont(font)
        self.addmanual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addmanual.setStyleSheet("\n"
"QPushButton{\n"
"    background-color: rgb(100, 173, 173);\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    font-weight: bold;\n"
"    border-bottom: 2px solid #444;\n"
"    border-right: 2px solid #444;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(82, 143, 145);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 135, 135); \n"
"    border-bottom: 1px solid #508080;\n"
"    border-right: 1px solid #508080;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Plusicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addmanual.setIcon(icon1)
        self.addmanual.setIconSize(QtCore.QSize(50, 50))
        self.addmanual.setObjectName("addmanual")
        self.horizontalLayout_2.addWidget(self.addmanual)
        self.protein = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protein.sizePolicy().hasHeightForWidth())
        self.protein.setSizePolicy(sizePolicy)
        self.protein.setMaximumSize(QtCore.QSize(109, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.protein.setFont(font)
        self.protein.setStyleSheet("QWidget {\n"
"    border: 2px solid grey;\n"
"    background-color: #F0FDFA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"Qlabel {\n"
"    border: none; \n"
"    background-color: none;\n"
"}")
        self.protein.setObjectName("protein")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.protein)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.totalprotein = QtWidgets.QLabel(self.protein)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.totalprotein.setFont(font)
        self.totalprotein.setStyleSheet("color: rgb(153, 153, 153);\n"
"border: none;")
        self.totalprotein.setAlignment(QtCore.Qt.AlignCenter)
        self.totalprotein.setObjectName("totalprotein")
        self.verticalLayout_6.addWidget(self.totalprotein)
        self.proteingram = QtWidgets.QLabel(self.protein)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proteingram.sizePolicy().hasHeightForWidth())
        self.proteingram.setSizePolicy(sizePolicy)
        self.proteingram.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.proteingram.setFont(font)
        self.proteingram.setStyleSheet("color: rgb(224, 185, 86);\n"
"border: none;")
        self.proteingram.setAlignment(QtCore.Qt.AlignCenter)
        self.proteingram.setObjectName("proteingram")
        self.verticalLayout_6.addWidget(self.proteingram)
        self.horizontalLayout_2.addWidget(self.protein)
        self.carbs = QtWidgets.QWidget(self.widget)
        self.carbs.setMaximumSize(QtCore.QSize(109, 60))
        self.carbs.setStyleSheet("QWidget {\n"
"    border: 2px solid grey;\n"
"    background-color: #F0FDFA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"Qlabel {\n"
"    border: none; \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.carbs.setObjectName("carbs")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.carbs)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.totalcarbs = QtWidgets.QLabel(self.carbs)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.totalcarbs.setFont(font)
        self.totalcarbs.setStyleSheet("color: rgb(153, 153, 153);\n"
"border: none;")
        self.totalcarbs.setAlignment(QtCore.Qt.AlignCenter)
        self.totalcarbs.setObjectName("totalcarbs")
        self.verticalLayout_7.addWidget(self.totalcarbs)
        self.carbsgram = QtWidgets.QLabel(self.carbs)
        self.carbsgram.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.carbsgram.setFont(font)
        self.carbsgram.setStyleSheet("color: rgb(224, 185, 86);\n"
"border: none;")
        self.carbsgram.setAlignment(QtCore.Qt.AlignCenter)
        self.carbsgram.setObjectName("carbsgram")
        self.verticalLayout_7.addWidget(self.carbsgram)
        self.horizontalLayout_2.addWidget(self.carbs)
        self.fat = QtWidgets.QWidget(self.widget)
        self.fat.setMaximumSize(QtCore.QSize(109, 60))
        self.fat.setStyleSheet("QWidget {\n"
"    border: 2px solid grey;\n"
"    background-color: #F0FDFA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"Qlabel {\n"
"    border: none; \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.fat.setObjectName("fat")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fat)
        self.verticalLayout_8.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.totalfat = QtWidgets.QLabel(self.fat)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.totalfat.setFont(font)
        self.totalfat.setStyleSheet("color: rgb(153, 153, 153);\n"
"border: none;")
        self.totalfat.setAlignment(QtCore.Qt.AlignCenter)
        self.totalfat.setObjectName("totalfat")
        self.verticalLayout_8.addWidget(self.totalfat)
        self.fatgram = QtWidgets.QLabel(self.fat)
        self.fatgram.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fatgram.setFont(font)
        self.fatgram.setStyleSheet("color: rgb(224, 185, 86);\n"
"border: none;")
        self.fatgram.setAlignment(QtCore.Qt.AlignCenter)
        self.fatgram.setObjectName("fatgram")
        self.verticalLayout_8.addWidget(self.fatgram)
        self.horizontalLayout_2.addWidget(self.fat)
        self.verticalLayout_9.addWidget(self.widget)
        self.table = QtWidgets.QTableWidget(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(238, 235, 219);\n"
"    border: 1px solid #e0e0e0; \n"
"    gridline-color: #f0f0f0; \n"
"    font-size: 10pt;\n"
"    selection-background-color: #cfe8fc;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(255, 227, 162);\n"
"    color: #333333;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"    border-right: 1px solid #e0e0e0;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last-section {\n"
"    border-right: none;\n"
"}")
        self.table.setObjectName("table")
        self.table.setColumnCount(8)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        self.table.horizontalHeader().setDefaultSectionSize(130)
        self.verticalLayout_9.addWidget(self.table)
        self.verticalLayout.addWidget(self.main_body)
        self.menu_bar = QtWidgets.QWidget(self.centralwidget)
        self.menu_bar.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_bar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_bar.setStyleSheet("background-color: rgb(82, 143, 145);")
        self.menu_bar.setObjectName("menu_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_bar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.home = QtWidgets.QPushButton(self.menu_bar)
        self.home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Homelogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon2)
        self.home.setIconSize(QtCore.QSize(14, 14))
        self.home.setCheckable(False)
        self.home.setObjectName("home")
        self.horizontalLayout_3.addWidget(self.home)
        self.foodlog = QtWidgets.QPushButton(self.menu_bar)
        self.foodlog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.foodlog.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Foodlog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.foodlog.setIcon(icon3)
        self.foodlog.setIconSize(QtCore.QSize(14, 14))
        self.foodlog.setObjectName("foodlog")
        self.horizontalLayout_3.addWidget(self.foodlog)
        self.progress = QtWidgets.QPushButton(self.menu_bar)
        self.progress.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.progress.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Progresslogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.progress.setIcon(icon4)
        self.progress.setIconSize(QtCore.QSize(14, 14))
        self.progress.setObjectName("progress")
        self.horizontalLayout_3.addWidget(self.progress)
        spacerItem = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.menu_bar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setPixmap(QtGui.QPixmap("Logokecil.png"))
        self.consumed.setText(_translate("MainWindow", "Consumed"))
        self.calorie_2.setText(_translate("MainWindow", "550 cal"))
        self.goal.setText(_translate("MainWindow", "Goal"))
        self.calorie_3.setText(_translate("MainWindow", "550 cal"))
        self.remaining.setText(_translate("MainWindow", "Remaining"))
        self.calorie.setText(_translate("MainWindow", "550 cal"))
        self.searchfood.setText(_translate("MainWindow", "Search Food"))
        self.addmanual.setText(_translate("MainWindow", "Add Manual"))
        self.totalprotein.setText(_translate("MainWindow", "Total Protein"))
        self.proteingram.setText(_translate("MainWindow", "550 gr"))
        self.totalcarbs.setText(_translate("MainWindow", "Total Carbs"))
        self.carbsgram.setText(_translate("MainWindow", "550 gr"))
        self.totalfat.setText(_translate("MainWindow", "Total Fat"))
        self.fatgram.setText(_translate("MainWindow", "550 gr"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Calories"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Protein"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fat"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Carbs"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Portion"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Options"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.foodlog.setText(_translate("MainWindow", "Food Log"))
        self.progress.setText(_translate("MainWindow", "Progress"))
import rsc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
