# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'foodlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Home_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 820)
        MainWindow.setWindowIcon(QtGui.QIcon("Logokecil.png"))
        MainWindow.setStyleSheet("background-color: rgb(254,251,234);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 45))
        self.header.setMaximumSize(QtCore.QSize(16777215, 45))
        self.header.setStyleSheet("")
        self.header.setObjectName("header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.line = QtWidgets.QFrame(self.header)
        self.line.setStyleSheet("background-color: rgb(82, 143, 145);")
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        
        self.main_body = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setObjectName("main_body")
        
        self.BreakfastLayout = QtWidgets.QLabel(self.main_body)
        self.BreakfastLayout.setGeometry(QtCore.QRect(293, 220, 140, 80))
        self.BreakfastLayout.setStyleSheet("border-radius:10px;\n"
"background:none;\n"
"background-color: rgb(179, 200, 99);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"padding-top:50px;")
        self.BreakfastLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.BreakfastLayout.setObjectName("BreakfastLayout")
        
        self.DisplayBreakfastLabel = QtWidgets.QLabel(self.main_body)
        self.DisplayBreakfastLabel.setGeometry(QtCore.QRect(303, 230, 120, 31))
        self.DisplayBreakfastLabel.setStyleSheet("background:none; border:1px solid black; border-radius:2px;")
        self.DisplayBreakfastLabel.setText("")
        self.DisplayBreakfastLabel.setObjectName("DisplayBreakfastLabel")
        
        self.LunchLayout = QtWidgets.QLabel(self.main_body)
        self.LunchLayout.setGeometry(QtCore.QRect(458, 220, 140, 80))
        self.LunchLayout.setStyleSheet("border-radius:10px;\n"
"background:none;\n"
"background-color: rgb(253, 169, 45);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"padding-top:50px;")
        self.LunchLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.LunchLayout.setObjectName("LunchLayout")
        
        self.DisplayLunchLabel = QtWidgets.QLabel(self.main_body)
        self.DisplayLunchLabel.setGeometry(QtCore.QRect(468, 230, 120, 31))
        self.DisplayLunchLabel.setStyleSheet("background:none; border:1px solid black; border-radius:2px;")
        self.DisplayLunchLabel.setText("")
        self.DisplayLunchLabel.setObjectName("DisplayLunchLabel")
        self.DinnerLayout = QtWidgets.QLabel(self.main_body)
        self.DinnerLayout.setGeometry(QtCore.QRect(623, 220, 140, 80))
        self.DinnerLayout.setStyleSheet("border-radius:10px;\n"
"background:none;\n"
"background-color: rgb(77, 112, 154);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"padding-top:50px;")
        self.DinnerLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.DinnerLayout.setObjectName("DinnerLayout")

        self.DisplayDinnerLabel = QtWidgets.QLabel(self.main_body)
        self.DisplayDinnerLabel.setGeometry(QtCore.QRect(633, 230, 120, 31))
        self.DisplayDinnerLabel.setStyleSheet("background:none; border:1px solid black; border-radius:2px;")
        self.DisplayDinnerLabel.setText("")
        self.DisplayDinnerLabel.setObjectName("DisplayDinnerLabel")

        self.CaloriBar = QtWidgets.QProgressBar(self.main_body)
        self.CaloriBar.setGeometry(QtCore.QRect(293, 335, 470, 35))
        self.CaloriBar.setStyleSheet("QProgressBar { background:none; border: 1.3px solid black; border-radius: 5px; text-align: center; } QProgressBar::chunk { background-color: rgb(250, 239, 209); }")
        self.CaloriBar.setMinimum(0)
        self.CaloriBar.setMaximum(9999)
        self.CaloriBar.setProperty("value", 0)
        self.CaloriBar.setTextVisible(True)
        self.CaloriBar.setObjectName("CaloriBar")
        
        self.TodayCaloriesLabel = QtWidgets.QLabel(self.main_body)
        self.TodayCaloriesLabel.setGeometry(QtCore.QRect(295, 340, 130, 21))
        self.TodayCaloriesLabel.setStyleSheet("background: none; font-weight:bold; font-size:7pt;")
        self.TodayCaloriesLabel.setObjectName("TodayCaloriesLabel")

        self.widget_userInfo = QtWidgets.QWidget(self.main_body)
        self.widget_userInfo.setGeometry(QtCore.QRect(0, 0, 290, 180))
        self.widget_userInfo.setStyleSheet("background:none; border:2px solid black;")
        self.widget_userInfo.setObjectName("widget_userInfo")
        
        self.Name_Label = QtWidgets.QLabel(self.widget_userInfo)
        self.Name_Label.setGeometry(QtCore.QRect(0, 0, 80, 36))
        self.Name_Label.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.Name_Label.setObjectName("Name_Label")
        
        self.DisplayNameLabel = QtWidgets.QLabel(self.widget_userInfo)
        self.DisplayNameLabel.setGeometry(QtCore.QRect(80, 0, 210, 36))
        self.DisplayNameLabel.setStyleSheet("background:none; font-weight:bold;")
        self.DisplayNameLabel.setText("")
        self.DisplayNameLabel.setObjectName("DisplayNameLabel")
        
        self.Agelabel = QtWidgets.QLabel(self.widget_userInfo)
        self.Agelabel.setGeometry(QtCore.QRect(0, 36, 80, 36))
        self.Agelabel.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.Agelabel.setObjectName("Agelabel")
        
        self.DisplayAgeLabel = QtWidgets.QLabel(self.widget_userInfo)
        self.DisplayAgeLabel.setGeometry(QtCore.QRect(80, 36, 210, 36))
        self.DisplayAgeLabel.setStyleSheet("background:none; font-weight:bold;")
        self.DisplayAgeLabel.setText("")
        self.DisplayAgeLabel.setObjectName("DisplayAgeLabel")
        
        self.GenderLabel = QtWidgets.QLabel(self.widget_userInfo)
        self.GenderLabel.setGeometry(QtCore.QRect(0, 72, 80, 36))
        self.GenderLabel.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.GenderLabel.setObjectName("GenderLabel")
        
        self.DisplayGenderLabel = QtWidgets.QLabel(self.widget_userInfo)
        self.DisplayGenderLabel.setGeometry(QtCore.QRect(80, 72, 210, 36))
        self.DisplayGenderLabel.setStyleSheet("background:none; font-weight:bold;")
        self.DisplayGenderLabel.setText("")
        self.DisplayGenderLabel.setObjectName("DisplayGenderLabel")
        
        self.Height_Label = QtWidgets.QLabel(self.widget_userInfo)
        self.Height_Label.setGeometry(QtCore.QRect(0, 108, 80, 36))
        self.Height_Label.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.Height_Label.setObjectName("Height_Label")
    
        self.DisplayHeightLabel = QtWidgets.QLabel(self.widget_userInfo)
        self.DisplayHeightLabel.setGeometry(QtCore.QRect(80, 108, 170, 36))
        self.DisplayHeightLabel.setStyleSheet("background:none; font-weight:bold;")
        self.DisplayHeightLabel.setText("")
        self.DisplayHeightLabel.setObjectName("DisplayHeightLabel")
        
        self.Cm = QtWidgets.QLabel(self.widget_userInfo)
        self.Cm.setGeometry(QtCore.QRect(250, 108, 40, 36))
        self.Cm.setStyleSheet("background:none; border:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold; padding-top:0.5px;")
        self.Cm.setObjectName("Cm")
        
        self.Weight_Label = QtWidgets.QLabel(self.widget_userInfo)
        self.Weight_Label.setGeometry(QtCore.QRect(0, 144, 80, 36))
        self.Weight_Label.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.Weight_Label.setObjectName("Weight_Label")
        
        self.DisplayWeightLabel = QtWidgets.QLabel(self.widget_userInfo)
        self.DisplayWeightLabel.setGeometry(QtCore.QRect(80, 144, 170, 36))
        self.DisplayWeightLabel.setStyleSheet("background:none; font-weight:bold;")
        self.DisplayWeightLabel.setText("")
        self.DisplayWeightLabel.setObjectName("DisplayWeightLabel")
        
        self.Kg = QtWidgets.QLabel(self.widget_userInfo)
        self.Kg.setGeometry(QtCore.QRect(250, 144, 40, 36))
        self.Kg.setStyleSheet("background:none; border-left:1px; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.Kg.setObjectName("Kg")
        
        self.WeightProgressLabel = QtWidgets.QLabel(self.main_body)
        self.WeightProgressLabel.setGeometry(QtCore.QRect(303, 420, 451, 151))
        self.WeightProgressLabel.setStyleSheet("border-radius:10px; background:none; background-color: rgb(184, 58, 43); font: 12pt \"MS Shell Dlg 2\"; font-weight:bold; padding-bottom:80px; padding-left:130px;")
        self.WeightProgressLabel.setObjectName("WeightProgressLabel")
        
        self.WeighProgressBar = QtWidgets.QProgressBar(self.main_body)
        self.WeighProgressBar.setGeometry(QtCore.QRect(323, 490, 411, 31))
        self.WeighProgressBar.setStyleSheet("QProgressBar {\n"
"     border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"     text-align: center;\n"
"     background-color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"     background-color: #85d4d1; \n"
"     width: 10px;\n"
"}")
        self.WeighProgressBar.setTextVisible(False)
        self.WeighProgressBar.setObjectName("WeighProgressBar")
        
        self.StartWeightLabel = QtWidgets.QLabel(self.main_body)
        self.StartWeightLabel.setGeometry(QtCore.QRect(313, 520, 51, 31))
        self.StartWeightLabel.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.StartWeightLabel.setObjectName("StartWeightLabel")
        
        self.GoalWeightLabel = QtWidgets.QLabel(self.main_body)
        self.GoalWeightLabel.setGeometry(QtCore.QRect(653, 520, 41, 31))
        self.GoalWeightLabel.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\"; font-weight:bold;")
        self.GoalWeightLabel.setObjectName("GoalWeightLabel")
        
        self.FatLogo = QtWidgets.QLabel(self.main_body)
        self.FatLogo.setGeometry(QtCore.QRect(323, 450, 41, 41))
        self.FatLogo.setStyleSheet("background:none; image: url(:/image/fatlogo.png);")
        self.FatLogo.setText("")
        self.FatLogo.setObjectName("FatLogo")
        
        self.Fitlogo = QtWidgets.QLabel(self.main_body)
        self.Fitlogo.setGeometry(QtCore.QRect(683, 440, 51, 61))
        self.Fitlogo.setStyleSheet("background:none; image: url(:/image/fitlogo.png);")
        self.Fitlogo.setText("")
        self.Fitlogo.setObjectName("Fitlogo")
        
        self.Kg_2 = QtWidgets.QLabel(self.main_body)
        self.Kg_2.setGeometry(QtCore.QRect(403, 520, 41, 31))
        self.Kg_2.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\";")
        self.Kg_2.setObjectName("Kg_2")
        
        self.Kg_3 = QtWidgets.QLabel(self.main_body)
        self.Kg_3.setGeometry(QtCore.QRect(730, 520, 41, 31))
        self.Kg_3.setStyleSheet("background:none; font: 75 9pt \"MS Shell Dlg 2\";")
        self.Kg_3.setObjectName("Kg_3")
        
        self.DisplayWeightLabel2 = QtWidgets.QLabel(self.main_body)
        self.DisplayWeightLabel2.setGeometry(QtCore.QRect(363, 520, 41, 31))
        self.DisplayWeightLabel2.setStyleSheet("background:none;")
        self.DisplayWeightLabel2.setText("")
        self.DisplayWeightLabel2.setObjectName("DisplayWeightLabel2")
        
        self.DisplayWeightLabel3 = QtWidgets.QLabel(self.main_body)
        self.DisplayWeightLabel3.setGeometry(QtCore.QRect(693, 520, 41, 31))
        self.DisplayWeightLabel3.setStyleSheet("background:none;")
        self.DisplayWeightLabel3.setText("")
        self.DisplayWeightLabel3.setObjectName("DisplayWeightLabel3")
        
        self.verticalLayout.addWidget(self.main_body)
        
        self.menu_bar = QtWidgets.QWidget(self.centralwidget)
        self.menu_bar.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_bar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_bar.setStyleSheet("background-color: rgb(82, 143, 145);")
        self.menu_bar.setObjectName("menu_bar")
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_bar)
        self.horizontalLayout_3.setContentsMargins(10, 5, 10, 5) 
        self.horizontalLayout_3.setSpacing(10) 
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.HomeButton = QtWidgets.QPushButton(self.menu_bar)
        self.HomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HomeButton.setStyleSheet("QPushButton { background-color: rgb(111, 192, 195); color: white; } QPushButton:hover { background-color: rgb(100, 173, 173); }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Homelogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeButton.setIcon(icon)
        self.HomeButton.setIconSize(QtCore.QSize(14, 14))
        self.HomeButton.setObjectName("home")
        self.horizontalLayout_3.addWidget(self.HomeButton)

        self.FoodlogButton = QtWidgets.QPushButton(self.menu_bar)
        self.FoodlogButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FoodlogButton.setStyleSheet("QPushButton { background-color: rgb(111, 192, 195); color: white; } QPushButton:hover { background-color: rgb(100, 173, 173); }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Foodlog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FoodlogButton.setIcon(icon1)
        self.FoodlogButton.setIconSize(QtCore.QSize(14, 14))
        self.FoodlogButton.setObjectName("Foodlog")
        self.horizontalLayout_3.addWidget(self.FoodlogButton)

        self.progress = QtWidgets.QPushButton(self.menu_bar)
        self.progress.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.progress.setStyleSheet("QPushButton { background-color: rgb(111, 192, 195); color: white; } QPushButton:hover { background-color: rgb(100, 173, 173); }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Progresslogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.progress.setIcon(icon2)
        self.progress.setIconSize(QtCore.QSize(16, 16))
        self.progress.setObjectName("progress")
        self.horizontalLayout_3.addWidget(self.progress)
        
        self.update_weight = QtWidgets.QPushButton(self.menu_bar)
        self.update_weight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_weight.setStyleSheet("QPushButton { background-color: rgb(111, 192, 195); color: white; } QPushButton:hover { background-color: rgb(100, 173, 173); }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("weighticon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_weight.setIcon(icon3)
        self.update_weight.setIconSize(QtCore.QSize(0, 0))
        self.update_weight.setObjectName("progress")
        self.horizontalLayout_3.addWidget(self.update_weight)
        
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)

        self.LogoutButton = QtWidgets.QPushButton(self.menu_bar)
        self.LogoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogoutButton.setStyleSheet("QPushButton { background-color: rgb(111, 192, 195); color: white; } QPushButton:hover { background-color: rgb(100, 173, 173); }")
        self.LogoutButton.setObjectName("logout")
        self.horizontalLayout_3.addWidget(self.LogoutButton)
        
        self.verticalLayout.addWidget(self.menu_bar, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyCal"))
        self.title.setPixmap(QtGui.QPixmap("Logokecil.png"))
        self.HomeButton.setText(_translate("MainWindow", "Home"))
        self.FoodlogButton.setText(_translate("MainWindow", "Food Log"))
        self.progress.setText(_translate("MainWindow", "Progress"))
        self.update_weight.setText(_translate("MainWindow", "Update Data"))
        self.LogoutButton.setText(_translate("MainWindow", "Log Out"))
        self.CaloriBar.setFormat(_translate("MainWindow", "%v"))
        self.BreakfastLayout.setText(_translate("MainWindow", "Breakfast (cal)"))
        self.LunchLayout.setText(_translate("MainWindow", "Lunch (cal)"))
        self.DinnerLayout.setText(_translate("MainWindow", "Dinner (cal)"))
        self.TodayCaloriesLabel.setText(_translate("MainWindow", "Today Calories"))
        self.Name_Label.setText(_translate("MainWindow", "Name"))
        self.Agelabel.setText(_translate("MainWindow", "Age"))
        self.GenderLabel.setText(_translate("MainWindow", "Gender"))
        self.Height_Label.setText(_translate("MainWindow", "Height "))
        self.Weight_Label.setText(_translate("MainWindow", "Weight"))
        self.Kg.setText(_translate("MainWindow", "Kg"))
        self.Cm.setText(_translate("MainWindow", "Cm"))
        self.WeightProgressLabel.setText(_translate("MainWindow", "Weight Progress"))
        self.StartWeightLabel.setText(_translate("MainWindow", "Start :"))
        self.GoalWeightLabel.setText(_translate("MainWindow", "Goal :"))
        self.Kg_2.setText(_translate("MainWindow", "Kg"))
        self.Kg_3.setText(_translate("MainWindow", "Kg"))
        
import rsc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Home_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
