# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import time

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setGeometry(0, 0, 1056, 820)
        Form.setStyleSheet("background:none;")
        
        self.inputNamauser = QtWidgets.QLineEdit(Form)
        self.inputNamauser.setGeometry(QtCore.QRect(353, 340, 350, 45))
        self.inputNamauser.setStyleSheet("background: none;\n"
"border: 1px solid black;\n"
"font-weight:bold;"
"")
        self.inputNamauser.setObjectName("inputNamauser")
        self.Login = QtWidgets.QLabel(Form)
        self.Login.setEnabled(True)
        self.Login.setGeometry(QtCore.QRect(500, 220, 200, 50))
        self.Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Login.setAutoFillBackground(False)
        self.Login.setStyleSheet("background:none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight:Bold;\n"
"\n"
"")
        self.Login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Login.setScaledContents(False)
        self.Login.setObjectName("Login")
        self.LoadingBar = QtWidgets.QProgressBar(Form)
        self.LoadingBar.setGeometry(QtCore.QRect(353, 290, 400, 30))
        self.LoadingBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.LoadingBar.setStatusTip("")
        self.LoadingBar.setStyleSheet("\n"
"\n"
"")
        self.LoadingBar.setValue(0)
        self.LoadingBar.setMaximum(100)
        self.LoadingBar.setTextVisible(True)
        self.LoadingBar.setInvertedAppearance(False)
        self.LoadingBar.setObjectName("LoadingBar")
        
        self.inputPassword = QtWidgets.QLineEdit(Form)
        self.inputPassword.setGeometry(QtCore.QRect(353, 400, 350, 45))
        self.inputPassword.setObjectName("inputPassword")
        self.inputPassword.setStyleSheet("border: 1px solid black;\n"
"font-weight:bold;"
"background:none;")
        
        self.Enterbutton = QtWidgets.QPushButton(Form)
        self.Enterbutton.setGeometry(QtCore.QRect(353, 470, 350, 45))
        self.Enterbutton.setStyleSheet("\n"
"padding:500px;\n"
"background-color: rgb(0, 255, 0);\n"
"background: none;\n"
"border: 1px solid black;\n"
"")
        self.Enterbutton.setObjectName("Enterbutton")
        
        self.backbutton = QtWidgets.QPushButton(Form)
        self.backbutton.setGeometry(QtCore.QRect(353, 525, 350, 45))
        self.backbutton.setStyleSheet("\n"
"padding:500px;\n"
"background-color: red;\n"
"background: none;\n"
"border: 1px solid black;\n"
"")
        self.backbutton.setObjectName("backbutton") 

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def progress(self):
        count = self.LoadingBar.value()
        for i in range(self.LoadingBar.maximum()):
            count += 1
            time.sleep(0.01)
            self.LoadingBar.setValue(count)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login Page"))
        self.inputNamauser.setPlaceholderText(_translate("Form", "Username"))
        self.Login.setText(_translate("Form", "Login"))
        self.inputPassword.setPlaceholderText(_translate("Form", "Password"))
        self.Enterbutton.setText(_translate("Form", "Enter"))
        self.backbutton.setText(_translate("Form", "Back"))       

import rsc         


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
