# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import time

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowIcon(QtGui.QIcon("Logokecil.png"))
        Form.setGeometry(0, 0, 1056, 820)
        Form.setStyleSheet("background:none;")

        self.titleImage = QtWidgets.QLabel(Form)
        self.titleImage.setGeometry(QtCore.QRect(228, 80, 600, 150)) 
        self.titleImage.setObjectName("titleImage")
        self.titleImage.setPixmap(QtGui.QPixmap("Logo.png"))
        self.titleImage.setAlignment(QtCore.Qt.AlignCenter) 
        
        self.inputNamauser = QtWidgets.QLineEdit(Form)
        self.inputNamauser.setGeometry(QtCore.QRect(353, 340, 350, 45))
        self.inputNamauser.setStyleSheet("background: none;\n"
"border: 1px solid black;\n"
"font-weight:bold;"
"")
        self.inputNamauser.setObjectName("inputNamauser")
        self.Login = QtWidgets.QLabel(Form)
        self.Login.setEnabled(True)
        self.Login.setGeometry(QtCore.QRect(500, 220, 200, 50))
        self.Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Login.setAutoFillBackground(False)
        self.Login.setStyleSheet("background:none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight:Bold;\n"
"\n"
"")
        self.Login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Login.setScaledContents(False)
        self.Login.setObjectName("Login")
        self.LoadingBar = QtWidgets.QProgressBar(Form)
        self.LoadingBar.setGeometry(QtCore.QRect(353, 290, 350, 30))
        self.LoadingBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.LoadingBar.setStatusTip("")
        self.LoadingBar.setStyleSheet("QProgressBar {\n"
"     border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"     text-align: center;\n"
"     background-color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"     background-color: #85d4d1; \n"
"     width: 10px;\n"
"}")
        self.LoadingBar.setValue(0)
        self.LoadingBar.setMaximum(100)
        self.LoadingBar.setTextVisible(True)
        self.LoadingBar.setInvertedAppearance(False)
        self.LoadingBar.setObjectName("LoadingBar")
        
        self.inputPassword = QtWidgets.QLineEdit(Form)
        self.inputPassword.setGeometry(QtCore.QRect(353, 400, 350, 45))
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.inputPassword.setStyleSheet("border: 1px solid black;\n"
"font-weight:bold;"
"background:none;")
        
        self.Enterbutton = QtWidgets.QPushButton(Form)
        self.Enterbutton.setGeometry(QtCore.QRect(353, 470, 350, 45))
        self.Enterbutton.setStyleSheet("QPushButton {\n"
"     background-color: #528f91; /* Warna utama */\n"
"     color: white;\n"
"     border: 1px solid #3E6B6D;\n"
"     border-radius: 5px;\n"
"     font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: #60A5A8; \n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: #4A8082; \n"
"}")
        self.Enterbutton.setObjectName("Enterbutton")
        
        self.backbutton = QtWidgets.QPushButton(Form)
        self.backbutton.setGeometry(QtCore.QRect(353, 525, 350, 45))
        self.backbutton.setStyleSheet("QPushButton {\n"
"     background-color: #E0E0E0; \n"
"     color: black;\n"
"     border: 1px solid #BDBDBD;\n"
"     border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: #EAEAEA;\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: #D6D6D6;\n"
"}")
        self.backbutton.setObjectName("backbutton") 

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def progress(self):
        count = self.LoadingBar.value()
        for i in range(self.LoadingBar.maximum()):
            count += 1
            time.sleep(0.01)
            self.LoadingBar.setValue(count)
            
            

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login Page"))
        self.inputNamauser.setPlaceholderText(_translate("Form", "Username"))
        self.Login.setText(_translate("Form", "Login"))
        self.inputPassword.setPlaceholderText(_translate("Form", "Password"))
        self.Enterbutton.setText(_translate("Form", "Enter"))
        self.backbutton.setText(_translate("Form", "Back"))       

import rsc         


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
