# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prelogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import rsc

class Prelogin_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(700,200,700, 700)
        MainWindow.setStyleSheet("background-color: rgb(254,251,234);")
        MainWindow.setFixedSize(1056,820)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        #self.centralwidget.setStyleSheet("background-image: url(:/image/BackgroundPrelogin.jpeg);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 150, 140, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/Component.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tombolYES = QtWidgets.QPushButton(self.centralwidget)
        self.tombolYES.setGeometry(QtCore.QRect(463, 420, 130, 50))
        self.tombolYES.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tombolYES.setStyleSheet("background-image:none;\n"
"background-color: rgb(255, 216, 139);\n"
"font-weight:Bold;\n"
"color: white;\n"
"\n"
"")
        self.tombolYES.setAutoRepeat(False)
        self.tombolYES.setAutoExclusive(False)
        self.tombolYES.setAutoDefault(False)
        self.tombolYES.setObjectName("tombolYES")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 300, 450, 51))
        self.label_2.setMinimumSize(QtCore.QSize(221, 0))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: black;\n")
        self.label_2.setObjectName("label_2")
        self.tombolNO = QtWidgets.QPushButton(self.centralwidget)
        self.tombolNO.setGeometry(QtCore.QRect(463, 490, 130, 50))
        self.tombolNO.setStyleSheet("background-image:none;\n"
"background-color: rgb(255, 0, 0);\n"
"font-weight:Bold;\n"
"color: white;\n"
"\n"
"\n"
"")
        self.tombolNO.setObjectName("tombolNO")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tombolYES.setText(_translate("MainWindow", "Yes"))
        self.label_2.setText(_translate("MainWindow", "Do you have account?"))
        self.tombolNO.setText(_translate("MainWindow", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Prelogin_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
