# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 820)
        MainWindow.setStyleSheet("background-color: rgb(254,251,234);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 45))
        self.header.setMaximumSize(QtCore.QSize(16777215, 45))
        self.header.setStyleSheet("")
        self.header.setObjectName("header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.line = QtWidgets.QFrame(self.header)
        self.line.setStyleSheet("background-color: rgb(82, 143, 145);")
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.main_body = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setStyleSheet("")
        self.main_body.setObjectName("main_body")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.main_body)
        self.frame.setStyleSheet("background-color: white;\n"
"border: 1px solid #DDDDDD;\n"
"border-radius: 10px;\n"
"padding: 1px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.weight_graph_placeholder = QtWidgets.QWidget(self.frame)
        self.weight_graph_placeholder.setObjectName("weight_graph_placeholder")
        self.verticalLayout_4.addWidget(self.weight_graph_placeholder)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("border: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.start_label = QtWidgets.QLabel(self.frame_5)
        self.start_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_label.setObjectName("start_label")
        self.verticalLayout_5.addWidget(self.start_label)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.current_label = QtWidgets.QLabel(self.frame_7)
        self.current_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_label.setObjectName("current_label")
        self.verticalLayout_6.addWidget(self.current_label)
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.goal_label = QtWidgets.QLabel(self.frame_6)
        self.goal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_label.setObjectName("goal_label")
        self.verticalLayout_7.addWidget(self.goal_label)
        self.horizontalLayout.addWidget(self.frame_6)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.main_body)
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 1px solid #DDDDDD;\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.calories_graph_placeholder = QtWidgets.QWidget(self.frame_2)
        self.calories_graph_placeholder.setObjectName("calories_graph_placeholder")
        self.verticalLayout_8.addWidget(self.calories_graph_placeholder)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("border: none;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setStyleSheet("background-color: green;\n"
"border-radius: 8px; \n"
"min-width: 16px; \n"
"min-height: 16px;\n"
"max-width: 16px;\n"
"max-height: 16px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setStyleSheet("background-color: orange;\n"
"border-radius: 8px; \n"
"min-width: 16px; \n"
"min-height: 16px;\n"
"max-width: 16px;\n"
"max-height: 16px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.frame_8)
        self.label_9.setStyleSheet("background-color: red;\n"
"border-radius: 8px; \n"
"min-width: 16px; \n"
"min-height: 16px;\n"
"max-width: 16px;\n"
"max-height: 16px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.main_body)
        self.frame_3.setStyleSheet("background-color: rgb(79, 204, 146);\n"
"border: 1px solid #DDDDDD;\n"
"border-radius: 10px;\n"
"padding: 1px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: none;color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setStyleSheet("border: none;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Kalenderlogo.png"))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        self.label_14.setStyleSheet("color: white;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.days_to_goal_label = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.days_to_goal_label.setFont(font)
        self.days_to_goal_label.setStyleSheet("color: white;")
        self.days_to_goal_label.setObjectName("days_to_goal_label")
        self.verticalLayout_10.addWidget(self.days_to_goal_label)
        self.horizontalLayout_5.addWidget(self.frame_12)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setStyleSheet("border: none;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setStyleSheet("border: none;color: white;")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.percentage_label = QtWidgets.QLabel(self.frame_11)
        self.percentage_label.setStyleSheet("color: white;\n"
"border: none;")
        self.percentage_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.percentage_label.setObjectName("percentage_label")
        self.horizontalLayout_6.addWidget(self.percentage_label)
        self.verticalLayout_11.addWidget(self.frame_11)
        self.progress_bar = QtWidgets.QProgressBar(self.frame_10)
        self.progress_bar.setStyleSheet("QProgressBar {\n"
"    qproperty-textVisible: false;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: white;\n"
"    border-radius: 8px;\n"
"}")
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_11.addWidget(self.progress_bar)
        self.verticalLayout_9.addWidget(self.frame_10)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.main_body)
        
        self.menu_bar = QtWidgets.QWidget(self.centralwidget)
        self.menu_bar.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_bar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_bar.setStyleSheet("background-color: rgb(82, 143, 145);")
        self.menu_bar.setObjectName("menu_bar")
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_bar)
        self.horizontalLayout_3.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.home_button = QtWidgets.QPushButton(self.menu_bar)
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Homelogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(14, 14))
        self.home_button.setCheckable(False)
        self.home_button.setObjectName("home_button")
        self.horizontalLayout_3.addWidget(self.home_button)
        
        self.foodlog_button = QtWidgets.QPushButton(self.menu_bar)
        self.foodlog_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.foodlog_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Foodlog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.foodlog_button.setIcon(icon1)
        self.foodlog_button.setIconSize(QtCore.QSize(14, 14))
        self.foodlog_button.setObjectName("foodlog_button")
        self.horizontalLayout_3.addWidget(self.foodlog_button)
        
        self.progress_button = QtWidgets.QPushButton(self.menu_bar)
        self.progress_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.progress_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Progresslogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.progress_button.setIcon(icon2)
        self.progress_button.setIconSize(QtCore.QSize(14, 14))
        self.progress_button.setObjectName("progress_button")
        self.horizontalLayout_3.addWidget(self.progress_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        '''self.logout_button = QtWidgets.QPushButton(self.menu_bar)
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_3.addWidget(self.logout_button)'''
        
        self.verticalLayout.addWidget(self.menu_bar, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "EasyCal."))
        self.label.setText(_translate("MainWindow", "Weight Progress"))
        self.label_2.setText(_translate("MainWindow", "Start"))
        self.start_label.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Current"))
        self.current_label.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Goal"))
        self.goal_label.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Calories Intake Trend"))
        self.label_5.setText(_translate("MainWindow", "Within Target"))
        self.label_7.setText(_translate("MainWindow", "Below Target"))
        self.label_10.setText(_translate("MainWindow", "Above Target"))
        self.label_12.setText(_translate("MainWindow", "Goal Achievment Prediction"))
        self.label_14.setText(_translate("MainWindow", "Estimated Time to Goal"))
        self.days_to_goal_label.setText(_translate("MainWindow", ".... days"))
        self.label_16.setText(_translate("MainWindow", "Progress"))
        self.percentage_label.setText(_translate("MainWindow", "...%"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.foodlog_button.setText(_translate("MainWindow", "Food Log"))
        self.progress_button.setText(_translate("MainWindow", "Progress"))
        
import rsc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
