# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchfood.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchfood(object):
    def setupUi(self, searchfood):
        searchfood.setObjectName("searchfood")
        searchfood.resize(512, 272)
        searchfood.setStyleSheet("background-color: rgb(254,251,234);")
        self.centralwidget = QtWidgets.QWidget(searchfood)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("background-color: white;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Add_button = QtWidgets.QPushButton(self.centralwidget)
        self.Add_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.Add_button.setObjectName("Add_button")
        self.horizontalLayout.addWidget(self.Add_button)
        self.Remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.Remove_button.setObjectName("Remove_button")
        self.horizontalLayout.addWidget(self.Remove_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.Cancel_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel_Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}")
        self.Cancel_Button.setObjectName("Cancel_Button")
        self.horizontalLayout.addWidget(self.Cancel_Button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setStyleSheet("background-color: white;")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 2, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setStyleSheet("background-color: white;")
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_2.addWidget(self.listWidget_2, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color: rgb(74, 130, 131);\n"
"font: 75 15pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        searchfood.setLayout(self.gridLayout_2)

        self.retranslateUi(searchfood)
        self.Cancel_Button.clicked.connect(searchfood.close)
        QtCore.QMetaObject.connectSlotsByName(searchfood)

    def retranslateUi(self, searchfood):
        _translate = QtCore.QCoreApplication.translate
        searchfood.setWindowTitle(_translate("Searchfood", "Search Food"))
        self.pushButton.setText(_translate("searchfood", "Search"))
        self.Add_button.setText(_translate("searchfood", "Add"))
        self.Remove_button.setText(_translate("searchfood", "Remove"))
        self.pushButton_4.setText(_translate("searchfood", "Confirm"))
        self.Cancel_Button.setText(_translate("searchfood", "Cancel"))
        self.label.setText(_translate("searchfood", "Your Meal:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchfood = QtWidgets.QDialog()
    ui = Ui_searchfood()
    ui.setupUi(searchfood)
    searchfood.show()
    sys.exit(app.exec_())
