# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Signup_Window(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 750)
        Form.setStyleSheet("#Form { border-image: url(:/image/Backgroundsignup.jpg); }")
        self.main_layout = QtWidgets.QVBoxLayout(Form)
        self.main_layout.setContentsMargins(150, 20, 150, 40)
        self.main_layout.setObjectName("main_layout")
        self.Signuplabel = QtWidgets.QLabel(Form)
        self.Signuplabel.setStyleSheet("background-color: none;\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"color: #333;")
        self.Signuplabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Signuplabel.setObjectName("Signuplabel")
        self.main_layout.addWidget(self.Signuplabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.main_layout.addItem(spacerItem)
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setSpacing(15)
        self.form_layout.setObjectName("form_layout")
        self.InputNamauser = QtWidgets.QLineEdit(Form)
        self.InputNamauser.setMinimumSize(QtCore.QSize(0, 40))
        self.InputNamauser.setStyleSheet("background-color: rgba(255, 255, 255, 0.8);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.InputNamauser.setObjectName("InputNamauser")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.InputNamauser)
        self.InputPassword = QtWidgets.QLineEdit(Form)
        self.InputPassword.setMinimumSize(QtCore.QSize(0, 40))
        self.InputPassword.setStyleSheet("background-color: rgba(255, 255, 255, 0.8);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.InputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.InputPassword.setObjectName("InputPassword")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.InputPassword)
        self.main_layout.addLayout(self.form_layout)
        self.Genderlabel = QtWidgets.QLabel(Form)
        self.Genderlabel.setStyleSheet("background-color: none;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"")
        self.Genderlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Genderlabel.setObjectName("Genderlabel")
        self.main_layout.addWidget(self.Genderlabel)
        self.gender_layout = QtWidgets.QHBoxLayout()
        self.gender_layout.setObjectName("gender_layout")
        self.Malebutton = QtWidgets.QPushButton(Form)
        self.Malebutton.setMinimumSize(QtCore.QSize(0, 40))
        self.Malebutton.setObjectName("Malebutton")
        self.gender_layout.addWidget(self.Malebutton)
        self.Femalebutton = QtWidgets.QPushButton(Form)
        self.Femalebutton.setMinimumSize(QtCore.QSize(0, 40))
        self.Femalebutton.setObjectName("Femalebutton")
        self.gender_layout.addWidget(self.Femalebutton)
        self.main_layout.addLayout(self.gender_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.main_layout.addItem(spacerItem1)
        self.data_form_layout = QtWidgets.QFormLayout()
        self.data_form_layout.setSpacing(10)
        self.data_form_layout.setObjectName("data_form_layout")
        self.AgeLabel = QtWidgets.QLabel(Form)
        self.AgeLabel.setObjectName("AgeLabel")
        self.data_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.AgeLabel)
        self.InputAgeuser = QtWidgets.QSpinBox(Form)
        self.InputAgeuser.setMinimumSize(QtCore.QSize(0, 30))
        self.InputAgeuser.setMaximum(150)
        self.InputAgeuser.setObjectName("InputAgeuser")
        self.data_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.InputAgeuser)
        self.Weightlabel = QtWidgets.QLabel(Form)
        self.Weightlabel.setObjectName("Weightlabel")
        self.data_form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Weightlabel)
        self.InputTBuser = QtWidgets.QDoubleSpinBox(Form)
        self.InputTBuser.setMinimumSize(QtCore.QSize(0, 30))
        self.InputTBuser.setMaximum(999.0)
        self.InputTBuser.setObjectName("InputTBuser")
        self.data_form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.InputTBuser)
        self.Heightlabel = QtWidgets.QLabel(Form)
        self.Heightlabel.setObjectName("Heightlabel")
        self.data_form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Heightlabel)
        self.InputBBuser = QtWidgets.QDoubleSpinBox(Form)
        self.InputBBuser.setMinimumSize(QtCore.QSize(0, 30))
        self.InputBBuser.setMaximum(999.0)
        self.InputBBuser.setObjectName("InputBBuser")
        self.data_form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.InputBBuser)
        self.Targetweightlabel = QtWidgets.QLabel(Form)
        self.Targetweightlabel.setObjectName("Targetweightlabel")
        self.data_form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Targetweightlabel)
        self.InputTargetBB = QtWidgets.QDoubleSpinBox(Form)
        self.InputTargetBB.setMinimumSize(QtCore.QSize(0, 30))
        self.InputTargetBB.setMaximum(999.0)
        self.InputTargetBB.setObjectName("InputTargetBB")
        self.data_form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.InputTargetBB)
        self.ActivityLabel = QtWidgets.QLabel(Form)
        self.ActivityLabel.setObjectName("ActivityLabel")
        self.data_form_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ActivityLabel)
        self.ListActivity = QtWidgets.QComboBox(Form)
        self.ListActivity.setMinimumSize(QtCore.QSize(0, 30))
        self.ListActivity.setObjectName("ListActivity")
        self.ListActivity.addItem("")
        self.ListActivity.addItem("")
        self.ListActivity.addItem("")
        self.ListActivity.addItem("")
        self.ListActivity.addItem("")
        self.data_form_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ListActivity)
        self.main_layout.addLayout(self.data_form_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem2)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.Savedatabutton = QtWidgets.QPushButton(Form)
        self.Savedatabutton.setMinimumSize(QtCore.QSize(0, 40))
        self.Savedatabutton.setObjectName("Savedatabutton")
        self.button_layout.addWidget(self.Savedatabutton)
        self.Backbutton = QtWidgets.QPushButton(Form)
        self.Backbutton.setMinimumSize(QtCore.QSize(0, 40))
        self.Backbutton.setObjectName("Backbutton")
        self.button_layout.addWidget(self.Backbutton)
        self.main_layout.addLayout(self.button_layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Signup"))
        self.Signuplabel.setText(_translate("Form", "Sign Up"))
        self.InputNamauser.setPlaceholderText(_translate("Form", "Masukkan Username"))
        self.InputPassword.setPlaceholderText(_translate("Form", "Masukkan Password"))
        self.Genderlabel.setText(_translate("Form", "Gender"))
        self.Malebutton.setText(_translate("Form", "Male"))
        self.Femalebutton.setText(_translate("Form", "Female"))
        self.AgeLabel.setText(_translate("Form", "Umur (Tahun)"))
        self.Weightlabel.setText(_translate("Form", "Berat Badan (kg)"))
        self.Heightlabel.setText(_translate("Form", "Tinggi Badan (cm)"))
        self.Targetweightlabel.setText(_translate("Form", "Target Berat Badan (kg)"))
        self.ActivityLabel.setText(_translate("Form", "Tingkat Aktivitas"))
        self.ListActivity.setItemText(0, _translate("Form", "Sangat Jarang (Sedentary)"))
        self.ListActivity.setItemText(1, _translate("Form", "Jarang (Lightly Active)"))
        self.ListActivity.setItemText(2, _translate("Form", "Cukup (Moderately Active)"))
        self.ListActivity.setItemText(3, _translate("Form", "Sering (Very Active)"))
        self.ListActivity.setItemText(4, _translate("Form", "Sangat Sering (Extra Active)"))
        self.Savedatabutton.setText(_translate("Form", "Save"))
        self.Backbutton.setText(_translate("Form", "Back"))
import rsc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Signup_Window()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
