# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Signup_Window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 700)
        Dialog.setStyleSheet("background-color: #f0f0f0;")
        self.Signuplabel = QtWidgets.QLabel(Dialog)
        self.Signuplabel.setGeometry(QtCore.QRect(175, 30, 450, 50))
        self.Signuplabel.setStyleSheet("background: none;\n"
"font: 75 24pt \"Segoe UI\";\n"
"font-weight:bold;\n"
"color: #333;")
        self.Signuplabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Signuplabel.setObjectName("Signuplabel")
        self.InputNamauser = QtWidgets.QLineEdit(Dialog)
        self.InputNamauser.setGeometry(QtCore.QRect(175, 100, 450, 45))
        self.InputNamauser.setStyleSheet("background-color: white;\n"
"border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"font: 11pt \"Segoe UI\";")
        self.InputNamauser.setObjectName("InputNamauser")
        self.InputPassword = QtWidgets.QLineEdit(Dialog)
        self.InputPassword.setGeometry(QtCore.QRect(175, 155, 450, 45))
        self.InputPassword.setStyleSheet("background-color: white;\n"
"border: 1px solid #ccc;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"font: 11pt \"Segoe UI\";")
        self.InputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.InputPassword.setObjectName("InputPassword")
        self.Genderlabel = QtWidgets.QLabel(Dialog)
        self.Genderlabel.setGeometry(QtCore.QRect(175, 220, 450, 30))
        self.Genderlabel.setStyleSheet("background: none;\n"
"font: 75 16pt \"Segoe UI\";\n"
"font-weight:bold;")
        self.Genderlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Genderlabel.setObjectName("Genderlabel")
        self.Malebutton = QtWidgets.QPushButton(Dialog)
        self.Malebutton.setGeometry(QtCore.QRect(175, 260, 220, 40))
        self.Malebutton.setStyleSheet("background-color: white; border: 1px solid #ccc; border-radius: 5px; font: 10pt \'Segoe UI\'; ")
        self.Malebutton.setObjectName("Malebutton")
        self.Femalebutton = QtWidgets.QPushButton(Dialog)
        self.Femalebutton.setGeometry(QtCore.QRect(405, 260, 220, 40))
        self.Femalebutton.setStyleSheet("background-color: white; border: 1px solid #ccc; border-radius: 5px; font: 10pt \'Segoe UI\';")
        self.Femalebutton.setObjectName("Femalebutton")
        self.AgeLabel = QtWidgets.QLabel(Dialog)
        self.AgeLabel.setGeometry(QtCore.QRect(175, 325, 180, 35))
        self.AgeLabel.setStyleSheet("background: none; font: 75 11pt \"Segoe UI\"; font-weight:bold;")
        self.AgeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AgeLabel.setObjectName("AgeLabel")
        self.InputAgeuser = QtWidgets.QSpinBox(Dialog)
        self.InputAgeuser.setGeometry(QtCore.QRect(365, 325, 260, 35))
        self.InputAgeuser.setMaximum(150)
        self.InputAgeuser.setObjectName("InputAgeuser")
        self.Heightlabel = QtWidgets.QLabel(Dialog)
        self.Heightlabel.setGeometry(QtCore.QRect(175, 370, 180, 35))
        self.Heightlabel.setStyleSheet("background: none; font: 75 11pt \"Segoe UI\"; font-weight:bold;")
        self.Heightlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Heightlabel.setObjectName("Heightlabel")
        self.InputTBuser = QtWidgets.QDoubleSpinBox(Dialog)
        self.InputTBuser.setGeometry(QtCore.QRect(365, 370, 260, 35))
        self.InputTBuser.setMaximum(9999.0)
        self.InputTBuser.setObjectName("InputTBuser")
        self.Weightlabel = QtWidgets.QLabel(Dialog)
        self.Weightlabel.setGeometry(QtCore.QRect(175, 415, 180, 35))
        self.Weightlabel.setStyleSheet("background: none; font: 75 11pt \"Segoe UI\"; font-weight:bold;")
        self.Weightlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weightlabel.setObjectName("Weightlabel")
        self.InputBBuser = QtWidgets.QDoubleSpinBox(Dialog)
        self.InputBBuser.setGeometry(QtCore.QRect(365, 415, 260, 35))
        self.InputBBuser.setMaximum(9999.0)
        self.InputBBuser.setObjectName("InputBBuser")
        self.Targetweightlabel = QtWidgets.QLabel(Dialog)
        self.Targetweightlabel.setGeometry(QtCore.QRect(175, 460, 180, 35))
        self.Targetweightlabel.setStyleSheet("background: none; font: 75 11pt \"Segoe UI\"; font-weight:bold;")
        self.Targetweightlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Targetweightlabel.setObjectName("Targetweightlabel")
        self.InputTargetBB = QtWidgets.QDoubleSpinBox(Dialog)
        self.InputTargetBB.setGeometry(QtCore.QRect(365, 460, 260, 35))
        self.InputTargetBB.setMaximum(9999.0)
        self.InputTargetBB.setObjectName("InputTargetBB")
        self.Activitylabel = QtWidgets.QLabel(Dialog)
        self.Activitylabel.setGeometry(QtCore.QRect(175, 505, 180, 35))
        self.Activitylabel.setStyleSheet("background: none; font: 75 11pt \"Segoe UI\"; font-weight:bold;")
        self.Activitylabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Activitylabel.setObjectName("Activitylabel")
        self.ActivityBox = QtWidgets.QComboBox(Dialog)
        self.ActivityBox.setGeometry(QtCore.QRect(365, 505, 260, 35))
        self.ActivityBox.setObjectName("ActivityBox")
        self.ActivityBox.addItem("")
        self.ActivityBox.addItem("")
        self.ActivityBox.addItem("")
        self.ActivityBox.addItem("")
        self.Weeklylabel = QtWidgets.QLabel(Dialog)
        self.Weeklylabel.setGeometry(QtCore.QRect(175, 550, 180, 35))
        self.Weeklylabel.setStyleSheet("background: none; font: 75 11pt \"Segoe UI\"; font-weight:bold;")
        self.Weeklylabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weeklylabel.setObjectName("Weeklylabel")
        self.WeeklyBox = QtWidgets.QComboBox(Dialog)
        self.WeeklyBox.setGeometry(QtCore.QRect(365, 550, 260, 35))
        self.WeeklyBox.setObjectName("WeeklyBox")
        self.WeeklyBox.addItem("")
        self.WeeklyBox.addItem("")
        self.WeeklyBox.addItem("")
        self.Savedatabutton = QtWidgets.QPushButton(Dialog)
        self.Savedatabutton.setGeometry(QtCore.QRect(175, 615, 220, 45))
        self.Savedatabutton.setStyleSheet("QPushButton { background-color: #528f91; color: white; border: none; border-radius: 5px; font-weight: bold; font-size: 11pt; }\n"
"QPushButton:hover { background-color: #60A5A8; }\n"
"QPushButton:pressed { background-color: #4A8082; }")
        self.Savedatabutton.setObjectName("Savedatabutton")
        self.Backbutton = QtWidgets.QPushButton(Dialog)
        self.Backbutton.setGeometry(QtCore.QRect(405, 615, 220, 45))
        self.Backbutton.setStyleSheet("QPushButton { background-color: #E0E0E0; color: black; border: 1px solid #BDBDBD; border-radius: 5px; font-size: 11pt; }\n"
"QPushButton:hover { background-color: #EAEAEA; }\n"
"QPushButton:pressed { background-color: #D6D6D6; }")
        self.Backbutton.setObjectName("Backbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sign Up"))
        self.Signuplabel.setText(_translate("Dialog", "Sign Up"))
        self.InputNamauser.setPlaceholderText(_translate("Dialog", "Username"))
        self.InputPassword.setPlaceholderText(_translate("Dialog", "Password"))
        self.Genderlabel.setText(_translate("Dialog", "Gender"))
        self.Malebutton.setText(_translate("Dialog", "Male"))
        self.Femalebutton.setText(_translate("Dialog", "Female"))
        self.AgeLabel.setText(_translate("Dialog", "Age:"))
        self.Heightlabel.setText(_translate("Dialog", "Height (cm):"))
        self.Weightlabel.setText(_translate("Dialog", "Weight (kg):"))
        self.Targetweightlabel.setText(_translate("Dialog", "Target (kg):"))
        self.Activitylabel.setText(_translate("Dialog", "Activity Level:"))
        self.ActivityBox.setItemText(0, _translate("Dialog", "Sedentary (no exercise)"))
        self.ActivityBox.setItemText(1, _translate("Dialog", "Light (1-3 times/week)"))
        self.ActivityBox.setItemText(2, _translate("Dialog", "Moderate (4-5 times/week)"))
        self.ActivityBox.setItemText(3, _translate("Dialog", "Very active(6-7 times/week)"))
        self.Weeklylabel.setText(_translate("Dialog", "Weekly Goal:"))
        self.WeeklyBox.setItemText(0, _translate("Dialog", "0.25 kg/week"))
        self.WeeklyBox.setItemText(1, _translate("Dialog", "0.5 kg/week"))
        self.WeeklyBox.setItemText(2, _translate("Dialog", "1.0 kg/week"))
        self.Savedatabutton.setText(_translate("Dialog", "Save"))
        self.Backbutton.setText(_translate("Dialog", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Signup_Window()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
