# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Signuppp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import rsc
class Signup_Window(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setStyleSheet("background:none;")
        Form.resize(700,750)
        
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setStyleSheet("image: url(:/image/Backgroundsignup.jpg);")
        self.centralwidget.setObjectName("centralwidget")
        
        self.Signuplabel = QtWidgets.QLabel(Form)
        self.Signuplabel.setGeometry(QtCore.QRect(300, 10, 120, 50))
        self.Signuplabel.setStyleSheet("background-color: none;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"")
        self.Signuplabel.setObjectName("Signuplabel")
        
        self.InputNamauser = QtWidgets.QLineEdit(Form)
        self.InputNamauser.setGeometry(QtCore.QRect(230, 110, 270, 40))
        self.InputNamauser.setObjectName("InputNamauser")
        self.InputNamauser.setStyleSheet("background: none;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        
        self.InputPassword = QtWidgets.QLineEdit(Form)
        self.InputPassword.setGeometry(QtCore.QRect(230, 160, 270, 40))
        self.InputPassword.setObjectName("InputPassword")
        self.InputPassword.setStyleSheet("background: none;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        
        self.Genderlabel = QtWidgets.QLabel(Form)
        self.Genderlabel.setGeometry(QtCore.QRect(310, 210, 120, 50))
        self.Genderlabel.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"font-weight:bold;\n"
"")
        self.Genderlabel.setObjectName("Genderlabel")
        
        self.Malebutton = QtWidgets.QPushButton(Form)
        self.Malebutton.setEnabled(True)
        self.Malebutton.setGeometry(QtCore.QRect(250, 270, 100, 40))
        self.Malebutton.setStyleSheet("\n"
"background: rgb(255, 255, 255);\n"
"padding: 500px")
        self.Malebutton.setObjectName("Malebutton")
        
        self.Femalebutton = QtWidgets.QPushButton(Form)
        self.Femalebutton.setGeometry(QtCore.QRect(380, 270, 100, 40))
        self.Femalebutton.setStyleSheet("background: rgb(255, 255, 255);\n"
"padding: 500px")
        self.Femalebutton.setObjectName("Femalebutton")
        
        self.AgeLabel = QtWidgets.QLabel(Form)
        self.AgeLabel.setGeometry(QtCore.QRect(260, 330, 60, 30))
        self.AgeLabel.setStyleSheet("image:none;\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background:rgb(255,255,255);\n"
"font-weight:bold;\n"
"border-bottom: 2px solid rgb(0, 0, 0);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"")
        self.AgeLabel.setObjectName("AgeLabel")
        self.Weightlabel = QtWidgets.QLabel(Form)
        self.Weightlabel.setGeometry(QtCore.QRect(210, 390, 150, 30))
        self.Weightlabel.setStyleSheet("image:none;\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background:rgb(255,255,255);\n"
"font-weight:bold;\n"
"border-bottom: 2px solid rgb(0, 0, 0);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"")
        self.Weightlabel.setObjectName("Weightlabel")
        self.Heightlabel = QtWidgets.QLabel(Form)
        self.Heightlabel.setGeometry(QtCore.QRect(210, 445, 150, 30))
        self.Heightlabel.setStyleSheet("image:none;\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background:rgb(255,255,255);\n"
"font-weight:bold;\n"
"border-bottom: 2px solid rgb(0, 0, 0);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"")
        self.Heightlabel.setObjectName("Heightlabel")
        
        self.Targetweightlabel = QtWidgets.QLabel(Form)
        self.Targetweightlabel.setGeometry(QtCore.QRect(170, 500, 220, 30))
        self.Targetweightlabel.setStyleSheet("image:none;\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background:rgb(255,255,255);\n"
"font-weight:bold;\n"
"border-bottom: 2px solid rgb(0, 0, 0);\n"
"border-top: 1px solid rgb(0, 0, 0);\n"
"border-left: 1px solid rgb(0, 0, 0);\n"
"border-right: 1px solid rgb(0, 0, 0);\n"
"image:none;\n"
"")
        self.Targetweightlabel.setObjectName("Targetweightlabel")
        
        self.InputAgeuser = QtWidgets.QSpinBox(Form)
        self.InputAgeuser.setGeometry(QtCore.QRect(405, 330, 100, 30))
        self.InputAgeuser.setMaximum(999)
        self.InputAgeuser.setObjectName("InputAgeuser")
        
        self.InputTBuser = QtWidgets.QDoubleSpinBox(Form)
        self.InputTBuser.setGeometry(QtCore.QRect(405, 390, 100, 30))
        self.InputTBuser.setMaximum(9999.0)
        self.InputTBuser.setObjectName("InputTBuser")
        
        self.InputBBuser = QtWidgets.QDoubleSpinBox(Form)
        self.InputBBuser.setGeometry(QtCore.QRect(405, 445, 100, 30))
        self.InputBBuser.setMaximum(9999.0)
        self.InputBBuser.setObjectName("InputBBuser")
        
        self.InputTargetBB = QtWidgets.QDoubleSpinBox(Form)
        self.InputTargetBB.setGeometry(QtCore.QRect(405, 500, 100, 30))
        self.InputTargetBB.setMaximum(9999.0)
        self.InputTargetBB.setObjectName("InputTargetBB")
        
        self.Savedatabutton = QtWidgets.QPushButton(Form)
        self.Savedatabutton.setGeometry(QtCore.QRect(230, 600, 100, 40))
        self.Savedatabutton.setStyleSheet("background: rgb(255, 255, 255);\n"
"padding: 500px")
        self.Savedatabutton.setObjectName("Savedatabutton")
        self.Backbutton = QtWidgets.QPushButton(Form)
        self.Backbutton.setGeometry(QtCore.QRect(380, 600, 100, 40))
        self.Backbutton.setStyleSheet("background: rgb(255, 255, 255);\n"
"padding: 500px")
        self.Backbutton.setObjectName("Backbutton")
        
        
        '''MainWindow.setCentralWidget(Form)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)'''

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Signup"))
        self.Signuplabel.setText(_translate("Form", "Sign up"))
        self.InputNamauser.setPlaceholderText(_translate("Form", "Input Username"))
        self.Genderlabel.setText(_translate("Form", "Gender"))
        self.Malebutton.setText(_translate("Form", "Male"))
        self.Femalebutton.setText(_translate("Form", "Female"))
        self.AgeLabel.setText(_translate("Form", "Age"))
        self.Weightlabel.setText(_translate("Form", "Weight (kg)"))
        self.Heightlabel.setText(_translate("Form", "Height (cm)"))
        self.Savedatabutton.setText(_translate("Form", "Save"))
        self.Backbutton.setText(_translate("Form", "Back"))
        self.Targetweightlabel.setText(_translate("Form", "Target Weight (kg)"))
        self.InputPassword.setPlaceholderText(_translate("Form", "Input Password"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Signup_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
