# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Updatedata.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(367, 331)
        Form.setStyleSheet("background-color: rgb(254,251,234);\n"
"")
        Form.setWindowIcon(QtGui.QIcon("Logokecil.png"))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(14)
        self.gridLayout.setObjectName("gridLayout")
        self.currentweight = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.currentweight.setFont(font)
        self.currentweight.setObjectName("currentweight")
        self.gridLayout.addWidget(self.currentweight, 1, 0, 1, 2)
        self.activity = QtWidgets.QComboBox(Form)
        self.activity.setStyleSheet("background-color: white;\n"
"alternate-background-color: rgb(232, 232, 232);\n"
"border: none;")
        self.activity.addItem("")
        self.activity.addItem("")
        self.activity.addItem("")
        self.activity.addItem("")
        self.activity.setObjectName("activity")
        self.gridLayout.addWidget(self.activity, 6, 0, 1, 5)
        self.editdata = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.editdata.setFont(font)
        self.editdata.setStyleSheet("color: rgb(82, 143, 145);")
        self.editdata.setAlignment(QtCore.Qt.AlignCenter)
        self.editdata.setObjectName("editdata")
        self.gridLayout.addWidget(self.editdata, 0, 0, 1, 5)
        self.targetweight = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.targetweight.setFont(font)
        self.targetweight.setObjectName("targetweight")
        self.gridLayout.addWidget(self.targetweight, 3, 0, 1, 1)
        self.currentweight_2 = QtWidgets.QDoubleSpinBox(Form)
        self.currentweight_2.setStyleSheet("background-color: white;")
        self.currentweight_2.setObjectName("currentweight_2")
        self.gridLayout.addWidget(self.currentweight_2, 2, 0, 1, 5)
        self.targetweight_2 = QtWidgets.QDoubleSpinBox(Form)
        self.targetweight_2.setStyleSheet("background-color: white;")
        self.targetweight_2.setObjectName("targetweight_2")
        self.gridLayout.addWidget(self.targetweight_2, 4, 0, 1, 5)
        self.activitylevel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.activitylevel.setFont(font)
        self.activitylevel.setObjectName("activitylevel")
        self.gridLayout.addWidget(self.activitylevel, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border-radius: 2px;\n"
"    border-bottom: 0.5px solid #444;\n"
"    border-right: 0.5px solid #444;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 135, 135); \n"
"    border-bottom: 0.25px solid #508080;\n"
"    border-right: 0.25px solid #508080;\n"
"}\n"
"")
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 8, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(63, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(63, 16777215))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(111, 192, 195);\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border-radius: 2px;\n"
"    border-bottom: 0.5px solid #444;\n"
"    border-right: 0.5px solid #444;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(100, 173, 173);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 135, 135); \n"
"    border-bottom: 0.25px solid #508080;\n"
"    border-right: 0.25px solid #508080;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Update Data"))
        self.currentweight.setText(_translate("Form", "Current Weight"))
        self.editdata.setText(_translate("Form", "EDIT DATA"))
        self.targetweight.setText(_translate("Form", "Target Weight"))
        self.activitylevel.setText(_translate("Form", "Activity Level"))
        self.activity.setItemText(0, _translate("Form", "Sedentary (no exercise)"))
        self.activity.setItemText(1, _translate("Form", "Light (1-3 times/week)"))
        self.activity.setItemText(2, _translate("Form", "Moderate (4-5 times/week)"))
        self.activity.setItemText(3, _translate("Form", "Very active(6-7 times/week)"))
        self.cancel.setText(_translate("Form", "Cancel"))
        self.pushButton.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
